name: "Build seedhodler Github Pages"

on:
  push:
    branches: 
      - dev

jobs:

  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Use node 20.x to build and deploy page
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    - run: |
        npm install
        npm run predeploy

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v4
      if: github.ref == 'refs/heads/dev'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build