name: "Build seedhodler nix"

on:
  push:
    branches: 
      - dev

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v27
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - uses: cachix/cachix-action@6a9a34cdd93d0ae4b4b59fd678660efb08109f2f  # v12
      with:
        name: seedhodler-cache
        authToken: '${{ secrets.CACHIX_KEY }}'

    - run: nix flake check -L
